/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardFunctionsIndexRouteImport } from './routes/dashboard.functions.index'
import { Route as DashboardFunctionsFunctionIdRouteImport } from './routes/dashboard.functions.$functionId'
import { Route as DashboardFunctionsNewRouteImport } from './routes/dashboard.functions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFunctionsIndexRoute = DashboardFunctionsIndexRouteImport.update({
  id: '/functions/',
  path: '/functions/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFunctionsFunctionIdRoute =
  DashboardFunctionsFunctionIdRouteImport.update({
    id: '/functions/$functionId',
    path: '/functions/$functionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFunctionsNewRoute = DashboardFunctionsNewRouteImport.update({
  id: '/functions/new',
  path: '/functions/new',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/functions/$functionId': typeof DashboardFunctionsFunctionIdRoute
  '/dashboard/functions/new': typeof DashboardFunctionsNewRoute
  '/dashboard/functions/': typeof DashboardFunctionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/functions/$functionId': typeof DashboardFunctionsFunctionIdRoute
  '/dashboard/functions/new': typeof DashboardFunctionsNewRoute
  '/dashboard/functions': typeof DashboardFunctionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/functions/$functionId': typeof DashboardFunctionsFunctionIdRoute
  '/dashboard/functions/new': typeof DashboardFunctionsNewRoute
  '/dashboard/functions/': typeof DashboardFunctionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard/'
    | '/dashboard/functions/$functionId'
    | '/dashboard/functions/new'
    | '/dashboard/functions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard'
    | '/dashboard/functions/$functionId'
    | '/dashboard/functions/new'
    | '/dashboard/functions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard/'
    | '/dashboard/functions/$functionId'
    | '/dashboard/functions/new'
    | '/dashboard/functions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/functions/': {
      id: '/dashboard/functions/'
      path: '/functions'
      fullPath: '/dashboard/functions/'
      preLoaderRoute: typeof DashboardFunctionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/functions/$functionId': {
      id: '/dashboard/functions/$functionId'
      path: '/functions/$functionId'
      fullPath: '/dashboard/functions/$functionId'
      preLoaderRoute: typeof DashboardFunctionsFunctionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/functions/new': {
      id: '/dashboard/functions/new'
      path: '/functions/new'
      fullPath: '/dashboard/functions/new'
      preLoaderRoute: typeof DashboardFunctionsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFunctionsFunctionIdRoute: typeof DashboardFunctionsFunctionIdRoute
  DashboardFunctionsNewRoute: typeof DashboardFunctionsNewRoute
  DashboardFunctionsIndexRoute: typeof DashboardFunctionsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFunctionsFunctionIdRoute: DashboardFunctionsFunctionIdRoute,
  DashboardFunctionsNewRoute: DashboardFunctionsNewRoute,
  DashboardFunctionsIndexRoute: DashboardFunctionsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
